service: maze-game
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${file(env.yml):stage}
  region: ${file(env.yml):region}
  environment:
    connectionsTable: maze-connections
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    gameStateTable: gamestate2
    playersGameStatesTable: playersgamestates
    domainName: 57wvdg47l5.execute-api.us-east-1.amazonaws.com
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "arn:aws:dynamodb:${self:provider.environment.region}:*:table/${self:provider.environment.connectionsTable}"
    - Effect: Allow
      Action: "*"
      Resource: "arn:aws:dynamodb:${self:provider.environment.region}:*:table/${self:provider.environment.gameStateTable}"
    - Effect: Allow
      Action: "*"
      Resource: "arn:aws:dynamodb:${self:provider.environment.region}:*:table/${self:provider.environment.playersGameStatesTable}"
    - Effect: Allow
      Action: "*"
      Resource: arn:aws:sqs:us-east-1:702407458234:*

package:
  excludeDevDependencies: true
  exclude:
    - node_modules/aws-sdk


functions:
  newGame:
    handler: handler.newGame
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
  onEndOfBuildTime:
    handler: handler.onEndOfBuildTime
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - endOfBuildTime
              - Arn
  onEndOfShowcase:
    handler: handler.onEndOfShowcase
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - endOfShowcase
              - Arn
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: handler.disconnect
    events:
      - websocket:
          route: $disconnect
  receivedMessage:
    handler: handler.receivedMessage
    events:
      - websocket:
          route: $default

resources:
  Resources:
    connectionsDynamodb:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: connectionId
            AttributeType: S
        KeySchema:
          -
            AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.connectionsTable}
    gamestateDynamodb1:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: reference
            AttributeType: S
        KeySchema:
          -
            AttributeName: reference
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.gameStateTable}
    playersGameStates:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: connectionId
            AttributeType: S
        KeySchema:
          -
            AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.playersGameStatesTable}
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
    endOfBuildTime:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "endOfBuildTime"
    endOfShowcase:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "endOfShowcase"
