service: aws-node-websockets
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: ${file(env.yml):stage}
  region: ${file(env.yml):region}
  environment:
    dynamodb: ${self:service}-${opt:stage, self:provider.stage}
    stage: ${self:provider.stage}
    region: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "arn:aws:dynamodb:${self:provider.environment.region}:*:table/${self:provider.environment.dynamodb}"

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: handler.disconnect
    events:
      - websocket:
          route: $disconnect
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default

resources:
  Resources:
    connectionsDynamodb:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: connectionId
            AttributeType: S
        KeySchema:
          -
            AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.dynamodb}
